FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime
ENV JUPYTER_CONFIG_DIR=/data/jupyter/
COPY requirements.txt ./

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt